version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:

  aad-ui:
    build: .
    image: sofwerx/aad-ui
    container_name: aad-ui
    hostname: aad-ui
    restart: always
    ports:
      - 3001:3001
    environment:
    networks:
      - default
    logging: *default-logging

